### PR TITLE
2021 spring update

### PR DESCRIPTION
**Pull request by lonnen**
This was a lot.

Requests is deprecated and this swaps it out for its own copy of node-fetch. There were also changes to cheerio and acorn. There was a lot of restructuring of the application code to make things easier to test and debug. 

Like other corsica plugins there is now a test suite but it only covers the non-corsica business logic. I'm reasonably sure that part is correct but where it gets data from or sends it back into corsica may be hiding something.

This also arbitrarily adopts the airbnb style guide for JS because eslint refuses to pick a default, so I chose something. I can change it but we should agree on a preferred one across the board if we swap it.

Like the other updates this adds CI and bumps the version up.

### CODE REVIEW

**Comment by mythmon** [comment]
That's a lot of commits.

It all looks good to me, a lot more robust than what was there before. I don't however see the Github CI running, either here or on your fork. Is that expected? Is there something I should do to get it to run?

**Comment by lonnen** [comment]
@mythmon I think it needs to be in main before it can run. When I looked back on the other PRs adopting GH Actions they got the green check mark but I suspect that happened after the fact and those check marks are tied to a the commit sha.

**Comment by mythmon** [comment]
It seems you were correct: https://github.com/mythmon/corsica-google-presentation/runs/2427912720

**Comment by lonnen** [comment]
you love to see it

**Comment by lonnen** [comment]
@mythmon can you publish this to npm when you get a chance?

**Comment by mythmon** [comment]
done

**Pull request merged**
